### ISSUE TITLE
Fatal error triggered in WordPress Admin

### ISSUE THREAD

**Issue by scottybo** [tlamedia/gtm-kit#613]
Hi guys,

We’re using The Events Calendar plugin, and one of the URLs called looks like this:

`/wp-admin/admin.php?page=tec-tickets-attendees&dialog=move_tickets&check=c2a77bc1c4&ticket_ids=111111&width=800&height=800&event_id=114506&`

Visiting this page triggers a Fatal Error in your plugin

`PHP Fatal error: Uncaught TypeError: TLA_Media\GTM_Kit\Admin\SetupWizard::enqueue_assets(): Argument #1 ($hook) must be of type string, null given, called in /var/web/site/public_html/wp-includes/class-wp-hook.php on line 324 and defined in /var/web/site/public_html/wp-content/plugins/gtm-kit/src/Admin/SetupWizard.php:121`

It looks like the function `enqueue_assets` in `wp-content/plugins/gtm-kit/src/Admin/SetupWizard.php` isn’t checking whether the `$hook` is set or not.

Please can you add a fix which checks if the `$hook` is set or not

```php
public function enqueue_assets( ?string $hook ): void {
		if ( empty($hook) || strpos( $hook, self::SLUG ) === false ) {
			return;
		}
```

**Comment by TorbenLundsgaard** [comment]
fixed in #614

**Comment by scottybo** [comment]
@TorbenLundsgaard I just checked this and the error is still happening and is causing a conflict with The Events Calendar plugin. Below is the code that fixes this

```php
<?php
/*
Plugin Name: GTM Kit Fix
Description: Fixes null hook issue in GTM Kit
Author: DCS Digital
Version: 1.0
*/

add_action('plugins_loaded', function () {
    if (is_admin() && isset($_GET['page']) && $_GET['page'] === 'tec-tickets-attendees') {
        // Remove the GTM Kit admin initialisation
        remove_action('plugins_loaded', 'TLA_Media\GTM_Kit\gtmkit_admin_init', 10);
    }
}, 5);
```
